
package org.savara.policyquote.policyquoteprocess;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.0
 * 2014-01-16T11:50:35.873+05:30
 * Generated source version: 2.7.0
 */

@WebFault(name = "policyQuoteFault", targetNamespace = "http://www.example.org/policyQuote")
public class TooManyAccidentsFault extends Exception {
    
    private org.example.policyquote.PolicyQuoteFault policyQuoteFault;

    public TooManyAccidentsFault() {
        super();
    }
    
    public TooManyAccidentsFault(String message) {
        super(message);
    }
    
    public TooManyAccidentsFault(String message, Throwable cause) {
        super(message, cause);
    }

    public TooManyAccidentsFault(String message, org.example.policyquote.PolicyQuoteFault policyQuoteFault) {
        super(message);
        this.policyQuoteFault = policyQuoteFault;
    }

    public TooManyAccidentsFault(String message, org.example.policyquote.PolicyQuoteFault policyQuoteFault, Throwable cause) {
        super(message, cause);
        this.policyQuoteFault = policyQuoteFault;
    }

    public org.example.policyquote.PolicyQuoteFault getFaultInfo() {
        return this.policyQuoteFault;
    }
}
