/*
 * Generated by Savara.
 */
package org.savara.policyquote.policyquoteprocess;

import java.io.StringWriter;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.namespace.QName;

import org.switchyard.common.xml.QNameUtil;
import org.switchyard.transform.Transformer;

public class TooManyAccidentsFaultProviderTransformer extends org.switchyard.transform.BaseTransformer<org.savara.policyquote.policyquoteprocess.TooManyAccidentsFault,String>
				implements Transformer<org.savara.policyquote.policyquoteprocess.TooManyAccidentsFault,String> {
    
	public QName getTo() {
		return (QName.valueOf("{http://www.example.org/policyQuote}policyQuoteFault"));
	}
	
	public String transform(org.savara.policyquote.policyquoteprocess.TooManyAccidentsFault type) {
		Marshaller marshaller;
		JAXBContext _jaxbContext;

		try {
			_jaxbContext = JAXBContext.newInstance("org.example.policyquote");
		} catch (JAXBException e) {
			throw new RuntimeException("Failed to create JAXBContext for '" + getFrom() + "'.", e);
		}

		try {
			marshaller = _jaxbContext.createMarshaller();
		} catch (JAXBException e) {
			throw new RuntimeException("Failed to create Marshaller for type '" + getFrom() + "'.", e);
		}

		try {
			StringWriter resultWriter = new StringWriter();
			Object javaObject = type.getFaultInfo();

			marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
			marshaller.marshal(javaObject, resultWriter);

			return (resultWriter.toString());
		} catch (JAXBException e) {
			throw new RuntimeException("Failed to unmarshall for type '" + getFrom() + "'.", e);
		}
	}
}
