package org.savara.policyquote.creditcheckservice;

import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2014-01-16T11:50:35.312+05:30
 * Generated source version: 2.7.0
 * 
 */
@XmlSeeAlso({com.creditagency.creditcheck.ObjectFactory.class})
public interface CreditCheckService {

    public com.creditagency.creditcheck.CreditCheckResponse creditCheck(
        com.creditagency.creditcheck.CreditCheckRequest content
    );
}
